/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.api;

import se.phaseshift.jira.rest.client.model.AnnouncementBannerConfiguration;
import se.phaseshift.jira.rest.client.model.AnnouncementBannerConfigurationUpdate;
import se.phaseshift.jira.rest.client.model.ErrorCollection;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AnnouncementBannerApi
 */
@Ignore
public class AnnouncementBannerApiTest {

    private final AnnouncementBannerApi api = new AnnouncementBannerApi();

    /**
     * Get announcement banner configuration
     *
     * Returns the current announcement banner configuration.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getBannerTest() throws Exception {
        AnnouncementBannerConfiguration response = api.getBanner();

        // TODO: test validations
    }
    /**
     * Update announcement banner configuration
     *
     * Updates the announcement banner configuration.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void setBannerTest() throws Exception {
        AnnouncementBannerConfigurationUpdate body = null;
        Object response = api.setBanner(body);

        // TODO: test validations
    }
}
