/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.api;

import se.phaseshift.jira.rest.client.model.DataClassificationLevelsBean;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ClassificationLevelsApi
 */
@Ignore
public class ClassificationLevelsApiTest {

    private final ClassificationLevelsApi api = new ClassificationLevelsApi();

    /**
     * Get all classification levels
     *
     * Returns all classification levels.  **[Permissions](#permissions) required:** None.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllUserDataClassificationLevelsTest() throws Exception {
        List<String> status = null;
        String orderBy = null;
        DataClassificationLevelsBean response = api.getAllUserDataClassificationLevels(status, orderBy);

        // TODO: test validations
    }
}
