/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.api;

import se.phaseshift.jira.rest.client.model.CustomFieldValueUpdateDetails;
import se.phaseshift.jira.rest.client.model.MultipleCustomFieldValuesUpdateDetails;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for IssueCustomFieldValuesAppsApi
 */
@Ignore
public class IssueCustomFieldValuesAppsApiTest {

    private final IssueCustomFieldValuesAppsApi api = new IssueCustomFieldValuesAppsApi();

    /**
     * Update custom field value
     *
     * Updates the value of a custom field on one or more issues.  Apps can only perform this operation on [custom fields](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field/) and [custom field types](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field-type/) declared in their own manifests.  **[Permissions](#permissions) required:** Only the app that owns the custom field or custom field type can update its values with this operation.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateCustomFieldValueTest() throws Exception {
        CustomFieldValueUpdateDetails body = null;
        String fieldIdOrKey = null;
        Boolean generateChangelog = null;
        Object response = api.updateCustomFieldValue(body, fieldIdOrKey, generateChangelog);

        // TODO: test validations
    }
    /**
     * Update custom fields
     *
     * Updates the value of one or more custom fields on one or more issues. Combinations of custom field and issue should be unique within the request.  Apps can only perform this operation on [custom fields](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field/) and [custom field types](https://developer.atlassian.com/platform/forge/manifest-reference/modules/jira-custom-field-type/) declared in their own manifests.  **[Permissions](#permissions) required:** Only the app that owns the custom field or custom field type can update its values with this operation.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateMultipleCustomFieldValuesTest() throws Exception {
        MultipleCustomFieldValuesUpdateDetails body = null;
        Boolean generateChangelog = null;
        Object response = api.updateMultipleCustomFieldValues(body, generateChangelog);

        // TODO: test validations
    }
}
