/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.api;

import se.phaseshift.jira.rest.client.model.JiraStatus;
import se.phaseshift.jira.rest.client.model.PageOfStatuses;
import se.phaseshift.jira.rest.client.model.StatusCreateRequest;
import se.phaseshift.jira.rest.client.model.StatusUpdateRequest;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for StatusApi
 */
@Ignore
public class StatusApiTest {

    private final StatusApi api = new StatusApi();

    /**
     * Bulk create statuses
     *
     * Creates statuses for a global or project scope.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission.](https://confluence.atlassian.com/x/yodKLg)  *  *Administer Jira* [project permission.](https://confluence.atlassian.com/x/yodKLg)
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createStatusesTest() throws Exception {
        StatusCreateRequest body = null;
        List<JiraStatus> response = api.createStatuses(body);

        // TODO: test validations
    }
    /**
     * Bulk delete Statuses
     *
     * Deletes statuses by ID.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission.](https://confluence.atlassian.com/x/yodKLg)  *  *Administer Jira* [project permission.](https://confluence.atlassian.com/x/yodKLg)
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteStatusesByIdTest() throws Exception {
        List<String> id = null;
        Object response = api.deleteStatusesById(id);

        // TODO: test validations
    }
    /**
     * Bulk get statuses
     *
     * Returns a list of the statuses specified by one or more status IDs.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission.](https://confluence.atlassian.com/x/yodKLg)  *  *Administer Jira* [project permission.](https://confluence.atlassian.com/x/yodKLg)
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getStatusesByIdTest() throws Exception {
        List<String> id = null;
        String expand = null;
        List<JiraStatus> response = api.getStatusesById(id, expand);

        // TODO: test validations
    }
    /**
     * Search statuses paginated
     *
     * Returns a [paginated](https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/#pagination) list of statuses that match a search on name or project.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission.](https://confluence.atlassian.com/x/yodKLg)  *  *Administer Jira* [project permission.](https://confluence.atlassian.com/x/yodKLg)
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void searchTest() throws Exception {
        String expand = null;
        String projectId = null;
        Long startAt = null;
        Integer maxResults = null;
        String searchString = null;
        String statusCategory = null;
        PageOfStatuses response = api.search(expand, projectId, startAt, maxResults, searchString, statusCategory);

        // TODO: test validations
    }
    /**
     * Bulk update statuses
     *
     * Updates statuses by ID.  **[Permissions](#permissions) required:**   *  *Administer projects* [project permission.](https://confluence.atlassian.com/x/yodKLg)  *  *Administer Jira* [project permission.](https://confluence.atlassian.com/x/yodKLg)
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateStatusesTest() throws Exception {
        StatusUpdateRequest body = null;
        Object response = api.updateStatuses(body);

        // TODO: test validations
    }
}
