/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import se.phaseshift.jira.rest.client.model.DateRangeFilterRequest;
/**
 * Details of a filter for exporting archived issues.
 */
@Schema(description = "Details of a filter for exporting archived issues.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class ArchivedIssuesFilterRequest extends HashMap<String, Object> {
  @SerializedName("archivedBy")
  private List<String> archivedBy = null;

  @SerializedName("archivedDateRange")
  private DateRangeFilterRequest archivedDateRange = null;

  @SerializedName("issueTypes")
  private List<String> issueTypes = null;

  @SerializedName("projects")
  private List<String> projects = null;

  @SerializedName("reporters")
  private List<String> reporters = null;

  public ArchivedIssuesFilterRequest archivedBy(List<String> archivedBy) {
    this.archivedBy = archivedBy;
    return this;
  }

  public ArchivedIssuesFilterRequest addArchivedByItem(String archivedByItem) {
    if (this.archivedBy == null) {
      this.archivedBy = new ArrayList<String>();
    }
    this.archivedBy.add(archivedByItem);
    return this;
  }

   /**
   * List archived issues archived by a specified account ID.
   * @return archivedBy
  **/
  @Schema(description = "List archived issues archived by a specified account ID.")
  public List<String> getArchivedBy() {
    return archivedBy;
  }

  public void setArchivedBy(List<String> archivedBy) {
    this.archivedBy = archivedBy;
  }

  public ArchivedIssuesFilterRequest archivedDateRange(DateRangeFilterRequest archivedDateRange) {
    this.archivedDateRange = archivedDateRange;
    return this;
  }

   /**
   * Get archivedDateRange
   * @return archivedDateRange
  **/
  @Schema(description = "")
  public DateRangeFilterRequest getArchivedDateRange() {
    return archivedDateRange;
  }

  public void setArchivedDateRange(DateRangeFilterRequest archivedDateRange) {
    this.archivedDateRange = archivedDateRange;
  }

  public ArchivedIssuesFilterRequest issueTypes(List<String> issueTypes) {
    this.issueTypes = issueTypes;
    return this;
  }

  public ArchivedIssuesFilterRequest addIssueTypesItem(String issueTypesItem) {
    if (this.issueTypes == null) {
      this.issueTypes = new ArrayList<String>();
    }
    this.issueTypes.add(issueTypesItem);
    return this;
  }

   /**
   * List archived issues with a specified issue type ID.
   * @return issueTypes
  **/
  @Schema(description = "List archived issues with a specified issue type ID.")
  public List<String> getIssueTypes() {
    return issueTypes;
  }

  public void setIssueTypes(List<String> issueTypes) {
    this.issueTypes = issueTypes;
  }

  public ArchivedIssuesFilterRequest projects(List<String> projects) {
    this.projects = projects;
    return this;
  }

  public ArchivedIssuesFilterRequest addProjectsItem(String projectsItem) {
    if (this.projects == null) {
      this.projects = new ArrayList<String>();
    }
    this.projects.add(projectsItem);
    return this;
  }

   /**
   * List archived issues with a specified project key.
   * @return projects
  **/
  @Schema(description = "List archived issues with a specified project key.")
  public List<String> getProjects() {
    return projects;
  }

  public void setProjects(List<String> projects) {
    this.projects = projects;
  }

  public ArchivedIssuesFilterRequest reporters(List<String> reporters) {
    this.reporters = reporters;
    return this;
  }

  public ArchivedIssuesFilterRequest addReportersItem(String reportersItem) {
    if (this.reporters == null) {
      this.reporters = new ArrayList<String>();
    }
    this.reporters.add(reportersItem);
    return this;
  }

   /**
   * List archived issues where the reporter is a specified account ID.
   * @return reporters
  **/
  @Schema(description = "List archived issues where the reporter is a specified account ID.")
  public List<String> getReporters() {
    return reporters;
  }

  public void setReporters(List<String> reporters) {
    this.reporters = reporters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArchivedIssuesFilterRequest archivedIssuesFilterRequest = (ArchivedIssuesFilterRequest) o;
    return Objects.equals(this.archivedBy, archivedIssuesFilterRequest.archivedBy) &&
        Objects.equals(this.archivedDateRange, archivedIssuesFilterRequest.archivedDateRange) &&
        Objects.equals(this.issueTypes, archivedIssuesFilterRequest.issueTypes) &&
        Objects.equals(this.projects, archivedIssuesFilterRequest.projects) &&
        Objects.equals(this.reporters, archivedIssuesFilterRequest.reporters) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(archivedBy, archivedDateRange, issueTypes, projects, reporters, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArchivedIssuesFilterRequest {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    archivedBy: ").append(toIndentedString(archivedBy)).append("\n");
    sb.append("    archivedDateRange: ").append(toIndentedString(archivedDateRange)).append("\n");
    sb.append("    issueTypes: ").append(toIndentedString(issueTypes)).append("\n");
    sb.append("    projects: ").append(toIndentedString(projects)).append("\n");
    sb.append("    reporters: ").append(toIndentedString(reporters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
