/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Details for changing owners of shareable entities
 */
@Schema(description = "Details for changing owners of shareable entities")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class BulkChangeOwnerDetails {
  @SerializedName("autofixName")
  private Boolean autofixName = null;

  @SerializedName("newOwner")
  private String newOwner = null;

  public BulkChangeOwnerDetails autofixName(Boolean autofixName) {
    this.autofixName = autofixName;
    return this;
  }

   /**
   * Whether the name is fixed automatically if it&#x27;s duplicated after changing owner.
   * @return autofixName
  **/
  @Schema(required = true, description = "Whether the name is fixed automatically if it's duplicated after changing owner.")
  public Boolean isAutofixName() {
    return autofixName;
  }

  public void setAutofixName(Boolean autofixName) {
    this.autofixName = autofixName;
  }

  public BulkChangeOwnerDetails newOwner(String newOwner) {
    this.newOwner = newOwner;
    return this;
  }

   /**
   * The account id of the new owner.
   * @return newOwner
  **/
  @Schema(required = true, description = "The account id of the new owner.")
  public String getNewOwner() {
    return newOwner;
  }

  public void setNewOwner(String newOwner) {
    this.newOwner = newOwner;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkChangeOwnerDetails bulkChangeOwnerDetails = (BulkChangeOwnerDetails) o;
    return Objects.equals(this.autofixName, bulkChangeOwnerDetails.autofixName) &&
        Objects.equals(this.newOwner, bulkChangeOwnerDetails.newOwner);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autofixName, newOwner);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkChangeOwnerDetails {\n");
    
    sb.append("    autofixName: ").append(toIndentedString(autofixName)).append("\n");
    sb.append("    newOwner: ").append(toIndentedString(newOwner)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
