/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import se.phaseshift.jira.rest.client.model.ErrorCollection;
/**
 * BulkOperationErrorResult
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class BulkOperationErrorResult {
  @SerializedName("elementErrors")
  private ErrorCollection elementErrors = null;

  @SerializedName("failedElementNumber")
  private Integer failedElementNumber = null;

  @SerializedName("status")
  private Integer status = null;

  public BulkOperationErrorResult elementErrors(ErrorCollection elementErrors) {
    this.elementErrors = elementErrors;
    return this;
  }

   /**
   * Get elementErrors
   * @return elementErrors
  **/
  @Schema(description = "")
  public ErrorCollection getElementErrors() {
    return elementErrors;
  }

  public void setElementErrors(ErrorCollection elementErrors) {
    this.elementErrors = elementErrors;
  }

  public BulkOperationErrorResult failedElementNumber(Integer failedElementNumber) {
    this.failedElementNumber = failedElementNumber;
    return this;
  }

   /**
   * Get failedElementNumber
   * @return failedElementNumber
  **/
  @Schema(description = "")
  public Integer getFailedElementNumber() {
    return failedElementNumber;
  }

  public void setFailedElementNumber(Integer failedElementNumber) {
    this.failedElementNumber = failedElementNumber;
  }

  public BulkOperationErrorResult status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkOperationErrorResult bulkOperationErrorResult = (BulkOperationErrorResult) o;
    return Objects.equals(this.elementErrors, bulkOperationErrorResult.elementErrors) &&
        Objects.equals(this.failedElementNumber, bulkOperationErrorResult.failedElementNumber) &&
        Objects.equals(this.status, bulkOperationErrorResult.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(elementErrors, failedElementNumber, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkOperationErrorResult {\n");
    
    sb.append("    elementErrors: ").append(toIndentedString(elementErrors)).append("\n");
    sb.append("    failedElementNumber: ").append(toIndentedString(failedElementNumber)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
