/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Details of a request to bulk edit shareable entity.
 */
@Schema(description = "Details of a request to bulk edit shareable entity.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class BulkEditShareableEntityRequest {
  /**
   * Allowed action for bulk edit shareable entity
   */
  @JsonAdapter(ActionEnum.Adapter.class)
  public enum ActionEnum {
    @SerializedName("changeOwner")
    CHANGEOWNER("changeOwner"),
    @SerializedName("changePermission")
    CHANGEPERMISSION("changePermission"),
    @SerializedName("addPermission")
    ADDPERMISSION("addPermission"),
    @SerializedName("removePermission")
    REMOVEPERMISSION("removePermission");

    private String value;

    ActionEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static ActionEnum fromValue(String input) {
      for (ActionEnum b : ActionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<ActionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ActionEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public ActionEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return ActionEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("action")
  private ActionEnum action = null;

  @SerializedName("changeOwnerDetails")
  private AllOfBulkEditShareableEntityRequestChangeOwnerDetails changeOwnerDetails = null;

  @SerializedName("entityIds")
  private List<Long> entityIds = new ArrayList<Long>();

  @SerializedName("extendAdminPermissions")
  private Boolean extendAdminPermissions = null;

  @SerializedName("permissionDetails")
  private AllOfBulkEditShareableEntityRequestPermissionDetails permissionDetails = null;

  public BulkEditShareableEntityRequest action(ActionEnum action) {
    this.action = action;
    return this;
  }

   /**
   * Allowed action for bulk edit shareable entity
   * @return action
  **/
  @Schema(required = true, description = "Allowed action for bulk edit shareable entity")
  public ActionEnum getAction() {
    return action;
  }

  public void setAction(ActionEnum action) {
    this.action = action;
  }

  public BulkEditShareableEntityRequest changeOwnerDetails(AllOfBulkEditShareableEntityRequestChangeOwnerDetails changeOwnerDetails) {
    this.changeOwnerDetails = changeOwnerDetails;
    return this;
  }

   /**
   * The details of change owner action.
   * @return changeOwnerDetails
  **/
  @Schema(description = "The details of change owner action.")
  public AllOfBulkEditShareableEntityRequestChangeOwnerDetails getChangeOwnerDetails() {
    return changeOwnerDetails;
  }

  public void setChangeOwnerDetails(AllOfBulkEditShareableEntityRequestChangeOwnerDetails changeOwnerDetails) {
    this.changeOwnerDetails = changeOwnerDetails;
  }

  public BulkEditShareableEntityRequest entityIds(List<Long> entityIds) {
    this.entityIds = entityIds;
    return this;
  }

  public BulkEditShareableEntityRequest addEntityIdsItem(Long entityIdsItem) {
    this.entityIds.add(entityIdsItem);
    return this;
  }

   /**
   * The id list of shareable entities to be changed.
   * @return entityIds
  **/
  @Schema(required = true, description = "The id list of shareable entities to be changed.")
  public List<Long> getEntityIds() {
    return entityIds;
  }

  public void setEntityIds(List<Long> entityIds) {
    this.entityIds = entityIds;
  }

  public BulkEditShareableEntityRequest extendAdminPermissions(Boolean extendAdminPermissions) {
    this.extendAdminPermissions = extendAdminPermissions;
    return this;
  }

   /**
   * Whether the actions are executed by users with Administer Jira global permission.
   * @return extendAdminPermissions
  **/
  @Schema(description = "Whether the actions are executed by users with Administer Jira global permission.")
  public Boolean isExtendAdminPermissions() {
    return extendAdminPermissions;
  }

  public void setExtendAdminPermissions(Boolean extendAdminPermissions) {
    this.extendAdminPermissions = extendAdminPermissions;
  }

  public BulkEditShareableEntityRequest permissionDetails(AllOfBulkEditShareableEntityRequestPermissionDetails permissionDetails) {
    this.permissionDetails = permissionDetails;
    return this;
  }

   /**
   * The permission details to be changed.
   * @return permissionDetails
  **/
  @Schema(description = "The permission details to be changed.")
  public AllOfBulkEditShareableEntityRequestPermissionDetails getPermissionDetails() {
    return permissionDetails;
  }

  public void setPermissionDetails(AllOfBulkEditShareableEntityRequestPermissionDetails permissionDetails) {
    this.permissionDetails = permissionDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkEditShareableEntityRequest bulkEditShareableEntityRequest = (BulkEditShareableEntityRequest) o;
    return Objects.equals(this.action, bulkEditShareableEntityRequest.action) &&
        Objects.equals(this.changeOwnerDetails, bulkEditShareableEntityRequest.changeOwnerDetails) &&
        Objects.equals(this.entityIds, bulkEditShareableEntityRequest.entityIds) &&
        Objects.equals(this.extendAdminPermissions, bulkEditShareableEntityRequest.extendAdminPermissions) &&
        Objects.equals(this.permissionDetails, bulkEditShareableEntityRequest.permissionDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, changeOwnerDetails, entityIds, extendAdminPermissions, permissionDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkEditShareableEntityRequest {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    changeOwnerDetails: ").append(toIndentedString(changeOwnerDetails)).append("\n");
    sb.append("    entityIds: ").append(toIndentedString(entityIds)).append("\n");
    sb.append("    extendAdminPermissions: ").append(toIndentedString(extendAdminPermissions)).append("\n");
    sb.append("    permissionDetails: ").append(toIndentedString(permissionDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
