/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * List issues archived within a specified date range.
 */
@Schema(description = "List issues archived within a specified date range.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class DateRangeFilterRequest {
  @SerializedName("dateAfter")
  private String dateAfter = null;

  @SerializedName("dateBefore")
  private String dateBefore = null;

  public DateRangeFilterRequest dateAfter(String dateAfter) {
    this.dateAfter = dateAfter;
    return this;
  }

   /**
   * List issues archived after a specified date, passed in the YYYY-MM-DD format.
   * @return dateAfter
  **/
  @Schema(required = true, description = "List issues archived after a specified date, passed in the YYYY-MM-DD format.")
  public String getDateAfter() {
    return dateAfter;
  }

  public void setDateAfter(String dateAfter) {
    this.dateAfter = dateAfter;
  }

  public DateRangeFilterRequest dateBefore(String dateBefore) {
    this.dateBefore = dateBefore;
    return this;
  }

   /**
   * List issues archived before a specified date provided in the YYYY-MM-DD format.
   * @return dateBefore
  **/
  @Schema(required = true, description = "List issues archived before a specified date provided in the YYYY-MM-DD format.")
  public String getDateBefore() {
    return dateBefore;
  }

  public void setDateBefore(String dateBefore) {
    this.dateBefore = dateBefore;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DateRangeFilterRequest dateRangeFilterRequest = (DateRangeFilterRequest) o;
    return Objects.equals(this.dateAfter, dateRangeFilterRequest.dateAfter) &&
        Objects.equals(this.dateBefore, dateRangeFilterRequest.dateBefore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateAfter, dateBefore);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DateRangeFilterRequest {\n");
    
    sb.append("    dateAfter: ").append(toIndentedString(dateAfter)).append("\n");
    sb.append("    dateBefore: ").append(toIndentedString(dateBefore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
