/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * EntityPropertyDetails
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class EntityPropertyDetails {
  @SerializedName("entityId")
  private BigDecimal entityId = null;

  @SerializedName("key")
  private String key = null;

  @SerializedName("value")
  private String value = null;

  public EntityPropertyDetails entityId(BigDecimal entityId) {
    this.entityId = entityId;
    return this;
  }

   /**
   * The entity property ID.
   * @return entityId
  **/
  @Schema(example = "123", required = true, description = "The entity property ID.")
  public BigDecimal getEntityId() {
    return entityId;
  }

  public void setEntityId(BigDecimal entityId) {
    this.entityId = entityId;
  }

  public EntityPropertyDetails key(String key) {
    this.key = key;
    return this;
  }

   /**
   * The entity property key.
   * @return key
  **/
  @Schema(example = "mykey", required = true, description = "The entity property key.")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public EntityPropertyDetails value(String value) {
    this.value = value;
    return this;
  }

   /**
   * The new value of the entity property.
   * @return value
  **/
  @Schema(example = "newValue", required = true, description = "The new value of the entity property.")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityPropertyDetails entityPropertyDetails = (EntityPropertyDetails) o;
    return Objects.equals(this.entityId, entityPropertyDetails.entityId) &&
        Objects.equals(this.key, entityPropertyDetails.key) &&
        Objects.equals(this.value, entityPropertyDetails.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entityId, key, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityPropertyDetails {\n");
    
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
