/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import se.phaseshift.jira.rest.client.model.FoundGroup;
/**
 * The list of groups found in a search, including header text (Showing X of Y matching groups) and total of matched groups.
 */
@Schema(description = "The list of groups found in a search, including header text (Showing X of Y matching groups) and total of matched groups.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class FoundGroups {
  @SerializedName("groups")
  private List<FoundGroup> groups = null;

  @SerializedName("header")
  private String header = null;

  @SerializedName("total")
  private Integer total = null;

  public FoundGroups groups(List<FoundGroup> groups) {
    this.groups = groups;
    return this;
  }

  public FoundGroups addGroupsItem(FoundGroup groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<FoundGroup>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  @Schema(description = "")
  public List<FoundGroup> getGroups() {
    return groups;
  }

  public void setGroups(List<FoundGroup> groups) {
    this.groups = groups;
  }

  public FoundGroups header(String header) {
    this.header = header;
    return this;
  }

   /**
   * Header text indicating the number of groups in the response and the total number of groups found in the search.
   * @return header
  **/
  @Schema(description = "Header text indicating the number of groups in the response and the total number of groups found in the search.")
  public String getHeader() {
    return header;
  }

  public void setHeader(String header) {
    this.header = header;
  }

  public FoundGroups total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * The total number of groups found in the search.
   * @return total
  **/
  @Schema(description = "The total number of groups found in the search.")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FoundGroups foundGroups = (FoundGroups) o;
    return Objects.equals(this.groups, foundGroups.groups) &&
        Objects.equals(this.header, foundGroups.header) &&
        Objects.equals(this.total, foundGroups.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groups, header, total);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FoundGroups {\n");
    
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    header: ").append(toIndentedString(header)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
