/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import se.phaseshift.jira.rest.client.model.StatusDetails;
/**
 * Status details for an issue type.
 */
@Schema(description = "Status details for an issue type.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class IssueTypeWithStatus {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("self")
  private String self = null;

  @SerializedName("statuses")
  private List<StatusDetails> statuses = new ArrayList<StatusDetails>();

  @SerializedName("subtask")
  private Boolean subtask = null;

   /**
   * The ID of the issue type.
   * @return id
  **/
  @Schema(required = true, description = "The ID of the issue type.")
  public String getId() {
    return id;
  }

   /**
   * The name of the issue type.
   * @return name
  **/
  @Schema(required = true, description = "The name of the issue type.")
  public String getName() {
    return name;
  }

   /**
   * The URL of the issue type&#x27;s status details.
   * @return self
  **/
  @Schema(required = true, description = "The URL of the issue type's status details.")
  public String getSelf() {
    return self;
  }

   /**
   * List of status details for the issue type.
   * @return statuses
  **/
  @Schema(required = true, description = "List of status details for the issue type.")
  public List<StatusDetails> getStatuses() {
    return statuses;
  }

   /**
   * Whether this issue type represents subtasks.
   * @return subtask
  **/
  @Schema(required = true, description = "Whether this issue type represents subtasks.")
  public Boolean isSubtask() {
    return subtask;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueTypeWithStatus issueTypeWithStatus = (IssueTypeWithStatus) o;
    return Objects.equals(this.id, issueTypeWithStatus.id) &&
        Objects.equals(this.name, issueTypeWithStatus.name) &&
        Objects.equals(this.self, issueTypeWithStatus.self) &&
        Objects.equals(this.statuses, issueTypeWithStatus.statuses) &&
        Objects.equals(this.subtask, issueTypeWithStatus.subtask);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, self, statuses, subtask);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueTypeWithStatus {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    statuses: ").append(toIndentedString(statuses)).append("\n");
    sb.append("    subtask: ").append(toIndentedString(subtask)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
