/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * A list of changelog IDs.
 */
@Schema(description = "A list of changelog IDs.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class IssueChangelogIds {
  @SerializedName("changelogIds")
  private List<Long> changelogIds = new ArrayList<Long>();

  public IssueChangelogIds changelogIds(List<Long> changelogIds) {
    this.changelogIds = changelogIds;
    return this;
  }

  public IssueChangelogIds addChangelogIdsItem(Long changelogIdsItem) {
    this.changelogIds.add(changelogIdsItem);
    return this;
  }

   /**
   * The list of changelog IDs.
   * @return changelogIds
  **/
  @Schema(required = true, description = "The list of changelog IDs.")
  public List<Long> getChangelogIds() {
    return changelogIds;
  }

  public void setChangelogIds(List<Long> changelogIds) {
    this.changelogIds = changelogIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueChangelogIds issueChangelogIds = (IssueChangelogIds) o;
    return Objects.equals(this.changelogIds, issueChangelogIds.changelogIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changelogIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueChangelogIds {\n");
    
    sb.append("    changelogIds: ").append(toIndentedString(changelogIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
