/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import se.phaseshift.jira.rest.client.model.Errors;
/**
 * Number of archived/unarchived issues and list of errors that occurred during the action, if any.
 */
@Schema(description = "Number of archived/unarchived issues and list of errors that occurred during the action, if any.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class IssueArchivalSyncResponse {
  @SerializedName("errors")
  private Errors errors = null;

  @SerializedName("numberOfIssuesUpdated")
  private Long numberOfIssuesUpdated = null;

  public IssueArchivalSyncResponse errors(Errors errors) {
    this.errors = errors;
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @Schema(description = "")
  public Errors getErrors() {
    return errors;
  }

  public void setErrors(Errors errors) {
    this.errors = errors;
  }

  public IssueArchivalSyncResponse numberOfIssuesUpdated(Long numberOfIssuesUpdated) {
    this.numberOfIssuesUpdated = numberOfIssuesUpdated;
    return this;
  }

   /**
   * Get numberOfIssuesUpdated
   * @return numberOfIssuesUpdated
  **/
  @Schema(description = "")
  public Long getNumberOfIssuesUpdated() {
    return numberOfIssuesUpdated;
  }

  public void setNumberOfIssuesUpdated(Long numberOfIssuesUpdated) {
    this.numberOfIssuesUpdated = numberOfIssuesUpdated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueArchivalSyncResponse issueArchivalSyncResponse = (IssueArchivalSyncResponse) o;
    return Objects.equals(this.errors, issueArchivalSyncResponse.errors) &&
        Objects.equals(this.numberOfIssuesUpdated, issueArchivalSyncResponse.numberOfIssuesUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errors, numberOfIssuesUpdated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueArchivalSyncResponse {\n");
    
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    numberOfIssuesUpdated: ").append(toIndentedString(numberOfIssuesUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
