/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import se.phaseshift.jira.rest.client.model.IssueEntityPropertiesForMultiUpdate;
/**
 * A list of issues and their respective properties to set or update. See [Entity properties](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/) for more information.
 */
@Schema(description = "A list of issues and their respective properties to set or update. See [Entity properties](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/) for more information.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class MultiIssueEntityProperties {
  @SerializedName("issues")
  private List<IssueEntityPropertiesForMultiUpdate> issues = null;

  public MultiIssueEntityProperties issues(List<IssueEntityPropertiesForMultiUpdate> issues) {
    this.issues = issues;
    return this;
  }

  public MultiIssueEntityProperties addIssuesItem(IssueEntityPropertiesForMultiUpdate issuesItem) {
    if (this.issues == null) {
      this.issues = new ArrayList<IssueEntityPropertiesForMultiUpdate>();
    }
    this.issues.add(issuesItem);
    return this;
  }

   /**
   * A list of issue IDs and their respective properties.
   * @return issues
  **/
  @Schema(description = "A list of issue IDs and their respective properties.")
  public List<IssueEntityPropertiesForMultiUpdate> getIssues() {
    return issues;
  }

  public void setIssues(List<IssueEntityPropertiesForMultiUpdate> issues) {
    this.issues = issues;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultiIssueEntityProperties multiIssueEntityProperties = (MultiIssueEntityProperties) o;
    return Objects.equals(this.issues, multiIssueEntityProperties.issues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issues);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultiIssueEntityProperties {\n");
    
    sb.append("    issues: ").append(toIndentedString(issues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
