/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import se.phaseshift.jira.rest.client.model.FieldCreateMetadata;
/**
 * A page of CreateMetaIssueType with Field.
 */
@Schema(description = "A page of CreateMetaIssueType with Field.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class PageOfCreateMetaIssueTypeWithField extends HashMap<String, Object> {
  @SerializedName("fields")
  private List<FieldCreateMetadata> fields = null;

  @SerializedName("maxResults")
  private Integer maxResults = null;

  @SerializedName("results")
  private List<FieldCreateMetadata> results = null;

  @SerializedName("startAt")
  private Long startAt = null;

  @SerializedName("total")
  private Long total = null;

   /**
   * The collection of FieldCreateMetaBeans.
   * @return fields
  **/
  @Schema(description = "The collection of FieldCreateMetaBeans.")
  public List<FieldCreateMetadata> getFields() {
    return fields;
  }

   /**
   * The maximum number of items to return per page.
   * @return maxResults
  **/
  @Schema(description = "The maximum number of items to return per page.")
  public Integer getMaxResults() {
    return maxResults;
  }

  public PageOfCreateMetaIssueTypeWithField results(List<FieldCreateMetadata> results) {
    this.results = results;
    return this;
  }

  public PageOfCreateMetaIssueTypeWithField addResultsItem(FieldCreateMetadata resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<FieldCreateMetadata>();
    }
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @Schema(description = "")
  public List<FieldCreateMetadata> getResults() {
    return results;
  }

  public void setResults(List<FieldCreateMetadata> results) {
    this.results = results;
  }

   /**
   * The index of the first item returned.
   * @return startAt
  **/
  @Schema(description = "The index of the first item returned.")
  public Long getStartAt() {
    return startAt;
  }

   /**
   * The total number of items in all pages.
   * @return total
  **/
  @Schema(description = "The total number of items in all pages.")
  public Long getTotal() {
    return total;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageOfCreateMetaIssueTypeWithField pageOfCreateMetaIssueTypeWithField = (PageOfCreateMetaIssueTypeWithField) o;
    return Objects.equals(this.fields, pageOfCreateMetaIssueTypeWithField.fields) &&
        Objects.equals(this.maxResults, pageOfCreateMetaIssueTypeWithField.maxResults) &&
        Objects.equals(this.results, pageOfCreateMetaIssueTypeWithField.results) &&
        Objects.equals(this.startAt, pageOfCreateMetaIssueTypeWithField.startAt) &&
        Objects.equals(this.total, pageOfCreateMetaIssueTypeWithField.total) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fields, maxResults, results, startAt, total, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageOfCreateMetaIssueTypeWithField {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    maxResults: ").append(toIndentedString(maxResults)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    startAt: ").append(toIndentedString(startAt)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
