/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Details about data policies for a project.
 */
@Schema(description = "Details about data policies for a project.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class ProjectWithDataPolicy {
  @SerializedName("dataPolicy")
  private AllOfProjectWithDataPolicyDataPolicy dataPolicy = null;

  @SerializedName("id")
  private Long id = null;

   /**
   * Data policy.
   * @return dataPolicy
  **/
  @Schema(description = "Data policy.")
  public AllOfProjectWithDataPolicyDataPolicy getDataPolicy() {
    return dataPolicy;
  }

   /**
   * The project ID.
   * @return id
  **/
  @Schema(description = "The project ID.")
  public Long getId() {
    return id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectWithDataPolicy projectWithDataPolicy = (ProjectWithDataPolicy) o;
    return Objects.equals(this.dataPolicy, projectWithDataPolicy.dataPolicy) &&
        Objects.equals(this.id, projectWithDataPolicy.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataPolicy, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectWithDataPolicy {\n");
    
    sb.append("    dataPolicy: ").append(toIndentedString(dataPolicy)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
