/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * The list of required status mappings by workflow.
 */
@Schema(description = "The list of required status mappings by workflow.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class RequiredMappingByWorkflows {
  @SerializedName("sourceWorkflowId")
  private String sourceWorkflowId = null;

  @SerializedName("statusIds")
  private List<String> statusIds = null;

  @SerializedName("targetWorkflowId")
  private String targetWorkflowId = null;

  public RequiredMappingByWorkflows sourceWorkflowId(String sourceWorkflowId) {
    this.sourceWorkflowId = sourceWorkflowId;
    return this;
  }

   /**
   * The ID of the source workflow.
   * @return sourceWorkflowId
  **/
  @Schema(description = "The ID of the source workflow.")
  public String getSourceWorkflowId() {
    return sourceWorkflowId;
  }

  public void setSourceWorkflowId(String sourceWorkflowId) {
    this.sourceWorkflowId = sourceWorkflowId;
  }

  public RequiredMappingByWorkflows statusIds(List<String> statusIds) {
    this.statusIds = statusIds;
    return this;
  }

  public RequiredMappingByWorkflows addStatusIdsItem(String statusIdsItem) {
    if (this.statusIds == null) {
      this.statusIds = new ArrayList<String>();
    }
    this.statusIds.add(statusIdsItem);
    return this;
  }

   /**
   * The status IDs requiring mapping.
   * @return statusIds
  **/
  @Schema(description = "The status IDs requiring mapping.")
  public List<String> getStatusIds() {
    return statusIds;
  }

  public void setStatusIds(List<String> statusIds) {
    this.statusIds = statusIds;
  }

  public RequiredMappingByWorkflows targetWorkflowId(String targetWorkflowId) {
    this.targetWorkflowId = targetWorkflowId;
    return this;
  }

   /**
   * The ID of the target workflow.
   * @return targetWorkflowId
  **/
  @Schema(description = "The ID of the target workflow.")
  public String getTargetWorkflowId() {
    return targetWorkflowId;
  }

  public void setTargetWorkflowId(String targetWorkflowId) {
    this.targetWorkflowId = targetWorkflowId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequiredMappingByWorkflows requiredMappingByWorkflows = (RequiredMappingByWorkflows) o;
    return Objects.equals(this.sourceWorkflowId, requiredMappingByWorkflows.sourceWorkflowId) &&
        Objects.equals(this.statusIds, requiredMappingByWorkflows.statusIds) &&
        Objects.equals(this.targetWorkflowId, requiredMappingByWorkflows.targetWorkflowId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceWorkflowId, statusIds, targetWorkflowId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequiredMappingByWorkflows {\n");
    
    sb.append("    sourceWorkflowId: ").append(toIndentedString(sourceWorkflowId)).append("\n");
    sb.append("    statusIds: ").append(toIndentedString(statusIds)).append("\n");
    sb.append("    targetWorkflowId: ").append(toIndentedString(targetWorkflowId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
