/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * The list of required status mappings by issue type.
 */
@Schema(description = "The list of required status mappings by issue type.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class RequiredMappingByIssueType {
  @SerializedName("issueTypeId")
  private String issueTypeId = null;

  @SerializedName("statusIds")
  private List<String> statusIds = null;

  public RequiredMappingByIssueType issueTypeId(String issueTypeId) {
    this.issueTypeId = issueTypeId;
    return this;
  }

   /**
   * The ID of the issue type.
   * @return issueTypeId
  **/
  @Schema(description = "The ID of the issue type.")
  public String getIssueTypeId() {
    return issueTypeId;
  }

  public void setIssueTypeId(String issueTypeId) {
    this.issueTypeId = issueTypeId;
  }

  public RequiredMappingByIssueType statusIds(List<String> statusIds) {
    this.statusIds = statusIds;
    return this;
  }

  public RequiredMappingByIssueType addStatusIdsItem(String statusIdsItem) {
    if (this.statusIds == null) {
      this.statusIds = new ArrayList<String>();
    }
    this.statusIds.add(statusIdsItem);
    return this;
  }

   /**
   * The status IDs requiring mapping.
   * @return statusIds
  **/
  @Schema(description = "The status IDs requiring mapping.")
  public List<String> getStatusIds() {
    return statusIds;
  }

  public void setStatusIds(List<String> statusIds) {
    this.statusIds = statusIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequiredMappingByIssueType requiredMappingByIssueType = (RequiredMappingByIssueType) o;
    return Objects.equals(this.issueTypeId, requiredMappingByIssueType.issueTypeId) &&
        Objects.equals(this.statusIds, requiredMappingByIssueType.statusIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issueTypeId, statusIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequiredMappingByIssueType {\n");
    
    sb.append("    issueTypeId: ").append(toIndentedString(issueTypeId)).append("\n");
    sb.append("    statusIds: ").append(toIndentedString(statusIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
