/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * An associated workflow scheme and project.
 */
@Schema(description = "An associated workflow scheme and project.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class WorkflowSchemeProjectAssociation {
  @SerializedName("projectId")
  private String projectId = null;

  @SerializedName("workflowSchemeId")
  private String workflowSchemeId = null;

  public WorkflowSchemeProjectAssociation projectId(String projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * The ID of the project.
   * @return projectId
  **/
  @Schema(required = true, description = "The ID of the project.")
  public String getProjectId() {
    return projectId;
  }

  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }

  public WorkflowSchemeProjectAssociation workflowSchemeId(String workflowSchemeId) {
    this.workflowSchemeId = workflowSchemeId;
    return this;
  }

   /**
   * The ID of the workflow scheme. If the workflow scheme ID is &#x60;null&#x60;, the operation assigns the default workflow scheme.
   * @return workflowSchemeId
  **/
  @Schema(description = "The ID of the workflow scheme. If the workflow scheme ID is `null`, the operation assigns the default workflow scheme.")
  public String getWorkflowSchemeId() {
    return workflowSchemeId;
  }

  public void setWorkflowSchemeId(String workflowSchemeId) {
    this.workflowSchemeId = workflowSchemeId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowSchemeProjectAssociation workflowSchemeProjectAssociation = (WorkflowSchemeProjectAssociation) o;
    return Objects.equals(this.projectId, workflowSchemeProjectAssociation.projectId) &&
        Objects.equals(this.workflowSchemeId, workflowSchemeProjectAssociation.workflowSchemeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, workflowSchemeId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowSchemeProjectAssociation {\n");
    
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    workflowSchemeId: ").append(toIndentedString(workflowSchemeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
