/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * The trigger configuration associated with a workflow.
 */
@Schema(description = "The trigger configuration associated with a workflow.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class WorkflowTrigger {
  @SerializedName("id")
  private String id = null;

  @SerializedName("parameters")
  private Map<String, String> parameters = new HashMap<String, String>();

  @SerializedName("ruleKey")
  private String ruleKey = null;

  public WorkflowTrigger id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The ID of the trigger.
   * @return id
  **/
  @Schema(description = "The ID of the trigger.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public WorkflowTrigger parameters(Map<String, String> parameters) {
    this.parameters = parameters;
    return this;
  }

  public WorkflowTrigger putParametersItem(String key, String parametersItem) {
    this.parameters.put(key, parametersItem);
    return this;
  }

   /**
   * The parameters of the trigger.
   * @return parameters
  **/
  @Schema(required = true, description = "The parameters of the trigger.")
  public Map<String, String> getParameters() {
    return parameters;
  }

  public void setParameters(Map<String, String> parameters) {
    this.parameters = parameters;
  }

  public WorkflowTrigger ruleKey(String ruleKey) {
    this.ruleKey = ruleKey;
    return this;
  }

   /**
   * The rule key of the trigger.
   * @return ruleKey
  **/
  @Schema(required = true, description = "The rule key of the trigger.")
  public String getRuleKey() {
    return ruleKey;
  }

  public void setRuleKey(String ruleKey) {
    this.ruleKey = ruleKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowTrigger workflowTrigger = (WorkflowTrigger) o;
    return Objects.equals(this.id, workflowTrigger.id) &&
        Objects.equals(this.parameters, workflowTrigger.parameters) &&
        Objects.equals(this.ruleKey, workflowTrigger.ruleKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, parameters, ruleKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowTrigger {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    ruleKey: ").append(toIndentedString(ruleKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
