/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import se.phaseshift.jira.rest.client.model.ProjectAndIssueTypePair;
/**
 * WorkflowReadRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class WorkflowReadRequest {
  @SerializedName("projectAndIssueTypes")
  private List<ProjectAndIssueTypePair> projectAndIssueTypes = null;

  @SerializedName("workflowIds")
  private List<String> workflowIds = null;

  @SerializedName("workflowNames")
  private List<String> workflowNames = null;

  public WorkflowReadRequest projectAndIssueTypes(List<ProjectAndIssueTypePair> projectAndIssueTypes) {
    this.projectAndIssueTypes = projectAndIssueTypes;
    return this;
  }

  public WorkflowReadRequest addProjectAndIssueTypesItem(ProjectAndIssueTypePair projectAndIssueTypesItem) {
    if (this.projectAndIssueTypes == null) {
      this.projectAndIssueTypes = new ArrayList<ProjectAndIssueTypePair>();
    }
    this.projectAndIssueTypes.add(projectAndIssueTypesItem);
    return this;
  }

   /**
   * The list of projects and issue types to query.
   * @return projectAndIssueTypes
  **/
  @Schema(description = "The list of projects and issue types to query.")
  public List<ProjectAndIssueTypePair> getProjectAndIssueTypes() {
    return projectAndIssueTypes;
  }

  public void setProjectAndIssueTypes(List<ProjectAndIssueTypePair> projectAndIssueTypes) {
    this.projectAndIssueTypes = projectAndIssueTypes;
  }

  public WorkflowReadRequest workflowIds(List<String> workflowIds) {
    this.workflowIds = workflowIds;
    return this;
  }

  public WorkflowReadRequest addWorkflowIdsItem(String workflowIdsItem) {
    if (this.workflowIds == null) {
      this.workflowIds = new ArrayList<String>();
    }
    this.workflowIds.add(workflowIdsItem);
    return this;
  }

   /**
   * The list of workflow IDs to query.
   * @return workflowIds
  **/
  @Schema(description = "The list of workflow IDs to query.")
  public List<String> getWorkflowIds() {
    return workflowIds;
  }

  public void setWorkflowIds(List<String> workflowIds) {
    this.workflowIds = workflowIds;
  }

  public WorkflowReadRequest workflowNames(List<String> workflowNames) {
    this.workflowNames = workflowNames;
    return this;
  }

  public WorkflowReadRequest addWorkflowNamesItem(String workflowNamesItem) {
    if (this.workflowNames == null) {
      this.workflowNames = new ArrayList<String>();
    }
    this.workflowNames.add(workflowNamesItem);
    return this;
  }

   /**
   * The list of workflow names to query.
   * @return workflowNames
  **/
  @Schema(description = "The list of workflow names to query.")
  public List<String> getWorkflowNames() {
    return workflowNames;
  }

  public void setWorkflowNames(List<String> workflowNames) {
    this.workflowNames = workflowNames;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowReadRequest workflowReadRequest = (WorkflowReadRequest) o;
    return Objects.equals(this.projectAndIssueTypes, workflowReadRequest.projectAndIssueTypes) &&
        Objects.equals(this.workflowIds, workflowReadRequest.workflowIds) &&
        Objects.equals(this.workflowNames, workflowReadRequest.workflowNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectAndIssueTypes, workflowIds, workflowNames);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowReadRequest {\n");
    
    sb.append("    projectAndIssueTypes: ").append(toIndentedString(projectAndIssueTypes)).append("\n");
    sb.append("    workflowIds: ").append(toIndentedString(workflowIds)).append("\n");
    sb.append("    workflowNames: ").append(toIndentedString(workflowNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
