/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * OpenAPI spec version: 1001.0.0-SNAPSHOT-d2bbf99a611e8c219fc0b1362289195366130541
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.phaseshift.jira.rest.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * The list of status mappings.
 */
@Schema(description = "The list of status mappings.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-04-17T13:21:14.321931+02:00[Europe/Stockholm]")

public class WorkflowAssociationStatusMapping {
  @SerializedName("newStatusId")
  private String newStatusId = null;

  @SerializedName("oldStatusId")
  private String oldStatusId = null;

  public WorkflowAssociationStatusMapping newStatusId(String newStatusId) {
    this.newStatusId = newStatusId;
    return this;
  }

   /**
   * The ID of the status in the new workflow.
   * @return newStatusId
  **/
  @Schema(required = true, description = "The ID of the status in the new workflow.")
  public String getNewStatusId() {
    return newStatusId;
  }

  public void setNewStatusId(String newStatusId) {
    this.newStatusId = newStatusId;
  }

  public WorkflowAssociationStatusMapping oldStatusId(String oldStatusId) {
    this.oldStatusId = oldStatusId;
    return this;
  }

   /**
   * The ID of the status in the old workflow that isn&#x27;t present in the new workflow.
   * @return oldStatusId
  **/
  @Schema(required = true, description = "The ID of the status in the old workflow that isn't present in the new workflow.")
  public String getOldStatusId() {
    return oldStatusId;
  }

  public void setOldStatusId(String oldStatusId) {
    this.oldStatusId = oldStatusId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowAssociationStatusMapping workflowAssociationStatusMapping = (WorkflowAssociationStatusMapping) o;
    return Objects.equals(this.newStatusId, workflowAssociationStatusMapping.newStatusId) &&
        Objects.equals(this.oldStatusId, workflowAssociationStatusMapping.oldStatusId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newStatusId, oldStatusId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowAssociationStatusMapping {\n");
    
    sb.append("    newStatusId: ").append(toIndentedString(newStatusId)).append("\n");
    sb.append("    oldStatusId: ").append(toIndentedString(oldStatusId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
